name: Lint
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Run Revive Action
      uses: morphy2k/revive-action@v2
      with:
        config: revive.toml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
