name: Lint
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Get linter
        run: go get -v -u github.com/mgechev/revive

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run linter
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          revive -config revive.toml -formatter friendly ./...
